apiVersion: v1
kind: Pod
metadata:
  name: lzy-server-test-pod
spec:
  containers:
  - name: lzy-server
    env:
      - name: LZY_SERVER_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    image: cr.yandex/crppns4pq490jrka0sth/lzy-server:latest
    ports:
      - containerPort: 8888
  hostNetwork: true
  dnsPolicy: Default

