scheduler:
  port: 2392

  base-env-default-image: ""
  max-servants-per-workflow: 1
  default-provisioning-limit: 1

  provisioning-limits:
    s: 10
    l: 10

  channel-manager-address: localhost:1234
  scheduler-address: localhost:2392  # ???
  allocator-address: localhost:1234
  servant-image: lzy-servant

  thread-allocator:
    enabled: true
    servant-jar-file: ""
    servant-class-name: "ai.lzy.servant.BashApi"

  docker-allocator:
    enabled: false

  kuber-allocator:
    enabled: false

  database:
    url: 'jdbc:h2:mem:testdb_scheduler;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false'
    #  url: 'jdbc:postgresql://localhost:5432/lzy-scheduler'
    username: 'test'
    password: ''
    min-pool-size: 1
    max-pool-size: 1
    enabled: true

  servant-processor:
    allocation-timeout: 100d
    configuring-timeout: 100d
    executing-heartbeat-period: 100d
    idle-heartbeat-period: 100d
    idle-timeout: 100ms
    servant-stop-timeout: 100ms
