replicaCount: 1
authorizerClassName: kafka.security.authorizer.AclAuthorizer
allowEveryoneIfNoAclFound: false
superUsers: "User:admin"

deleteTopicEnable: true
autoCreateTopicsEnable: false

externalAccess:
  enabled: true
  service:
    type: LoadBalancer
    ports:
      external: 9094
    annotations:
      "yandex.cloud/load-balancer-type": internal
      "yandex.cloud/subnet-id": ${subnet_id}
  autoDiscovery:
    enabled: true

serviceAccount:
  create: true

rbac:
  create: true

nodeSelector:
  "type": lzy

auth:
  clientProtocol: sasl_tls
  interBrokerProtocol: sasl
  tls:
    password: ${jks_password}
    existingSecrets:
      - ${jks_secret_name}
  sasl:
    jaas:
      clientUsers:
        - admin
      clientPasswords:
        - ${kafka_password}
      interBrokerUser: admin
      interBrokerPassword: ${kafka_password}

  jaas:
    zookeeperUser: zookeeperUser
    zookeeperPassword: zookeeperPassword

zookeeper:
  auth:
    client:
      enabled: true
      serverUsers: "zookeeperUser"
      serverPasswords: "zookeeperPassword"
      clientUser: zookeeperUser
      clientPassword: zookeeperPassword