apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: lzy
spec:
  kafka:
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: type
                      operator: In
                      values:
                        - lzy
    version: 3.4.0
    replicas: 1
    listeners:
      - name: scram
        port: 9092
        type: loadbalancer
        authentication:
          type: "scram-sha-512"
        tls: true
        configuration:
          bootstrap:
            annotations:
              "yandex.cloud/load-balancer-type": internal
              "yandex.cloud/subnet-id": ${subnet_id}
          brokers:
            - broker: 0
              annotations:
                "yandex.cloud/load-balancer-type": internal
                "yandex.cloud/subnet-id": ${subnet_id}
    authorization:
      type: simple
    config:
      auto.create.topics.enable: false
      inter.broker.protocol.version: "3.4"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 10Gi
          deleteClaim: false
  zookeeper:
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: type
                      operator: In
                      values:
                        - lzy
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  entityOperator:
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: type
                      operator: In
                      values:
                        - lzy
    tlsSidecar: {}
    topicOperator:
      watchedNamespace: default
      reconciliationIntervalSeconds: 60
      logging:
        type: inline
        loggers:
          rootLogger.level: "INFO"
    userOperator:
      watchedNamespace: default
      reconciliationIntervalSeconds: 60
      logging:
        type: inline
        loggers:
          rootLogger.level: INFO