apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: ${username}
  labels:
    strimzi.io/cluster: lzy
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          key: ${password_secret_key}
          name: ${password_secret}
  authorization:
    type: simple
    acls:
      - resource:
          type: cluster
        operations:
          - Alter
          - Create
          - AlterConfigs
          - Describe
          - DescribeConfigs
        host: "*"
      - resource:
          type: topic
          name: "*"
        operations:
          - Create
          - Delete
          - Describe
          - Alter
          - Read
          - Write
          - DescribeConfigs
          - AlterConfigs
      - resource:
          type: group
          name: "*"
        operations:
          - Delete
          - Describe
          - Read