Configuration:
  status: warn

  Appenders:
    File:
      name: LogFile
      fileName: ${sys:custom.log.file}
      PatternLayout:
        pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] [%t] %c{1} - %msg%n"

  Loggers:
    Root:
      level: info
      AppenderRef:
        - ref: LogFile