Configuration:
  status: warn

  Appenders:
    File:
      name: LogFile
      fileName: ${sys:custom.log.file}
      PatternLayout:
        pattern: "%d %-5level [%t] %notEmpty{{%notEmpty{user_id: \"%X{user_id}\"}%notEmpty{, task_id: \"%X{task_id}\"}}} %c{1.}: %msg%n%throwable"

  Loggers:
    Root:
      level: info
      AppenderRef:
        - ref: LogFile