# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ai.lzy.v1.workflow import workflow_service_pb2 as ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2


class LzyWorkflowServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateWorkflow = channel.unary_unary(
                '/ai.lzy.v1.workflow.LzyWorkflowService/CreateWorkflow',
                request_serializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.CreateWorkflowRequest.SerializeToString,
                response_deserializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.CreateWorkflowResponse.FromString,
                )
        self.AttachWorkflow = channel.unary_unary(
                '/ai.lzy.v1.workflow.LzyWorkflowService/AttachWorkflow',
                request_serializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.AttachWorkflowRequest.SerializeToString,
                response_deserializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.AttachWorkflowResponse.FromString,
                )
        self.FinishWorkflow = channel.unary_unary(
                '/ai.lzy.v1.workflow.LzyWorkflowService/FinishWorkflow',
                request_serializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.FinishWorkflowRequest.SerializeToString,
                response_deserializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.FinishWorkflowResponse.FromString,
                )
        self.DeleteWorkflow = channel.unary_unary(
                '/ai.lzy.v1.workflow.LzyWorkflowService/DeleteWorkflow',
                request_serializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.DeleteWorkflowRequest.SerializeToString,
                response_deserializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.DeleteWorkflowResponse.FromString,
                )
        self.ExecuteGraph = channel.unary_unary(
                '/ai.lzy.v1.workflow.LzyWorkflowService/ExecuteGraph',
                request_serializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.ExecuteGraphRequest.SerializeToString,
                response_deserializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.ExecuteGraphResponse.FromString,
                )
        self.GraphStatus = channel.unary_unary(
                '/ai.lzy.v1.workflow.LzyWorkflowService/GraphStatus',
                request_serializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.GraphStatusRequest.SerializeToString,
                response_deserializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.GraphStatusResponse.FromString,
                )
        self.StopGraph = channel.unary_unary(
                '/ai.lzy.v1.workflow.LzyWorkflowService/StopGraph',
                request_serializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.StopGraphRequest.SerializeToString,
                response_deserializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.StopGraphResponse.FromString,
                )
        self.ReadStdSlots = channel.unary_stream(
                '/ai.lzy.v1.workflow.LzyWorkflowService/ReadStdSlots',
                request_serializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.ReadStdSlotsRequest.SerializeToString,
                response_deserializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.ReadStdSlotsResponse.FromString,
                )
        self.GetAvailablePools = channel.unary_unary(
                '/ai.lzy.v1.workflow.LzyWorkflowService/GetAvailablePools',
                request_serializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.GetAvailablePoolsRequest.SerializeToString,
                response_deserializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.GetAvailablePoolsResponse.FromString,
                )


class LzyWorkflowServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AttachWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinishWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GraphStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadStdSlots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailablePools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LzyWorkflowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWorkflow,
                    request_deserializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.CreateWorkflowRequest.FromString,
                    response_serializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.CreateWorkflowResponse.SerializeToString,
            ),
            'AttachWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.AttachWorkflow,
                    request_deserializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.AttachWorkflowRequest.FromString,
                    response_serializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.AttachWorkflowResponse.SerializeToString,
            ),
            'FinishWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.FinishWorkflow,
                    request_deserializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.FinishWorkflowRequest.FromString,
                    response_serializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.FinishWorkflowResponse.SerializeToString,
            ),
            'DeleteWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteWorkflow,
                    request_deserializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.DeleteWorkflowRequest.FromString,
                    response_serializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.DeleteWorkflowResponse.SerializeToString,
            ),
            'ExecuteGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteGraph,
                    request_deserializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.ExecuteGraphRequest.FromString,
                    response_serializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.ExecuteGraphResponse.SerializeToString,
            ),
            'GraphStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GraphStatus,
                    request_deserializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.GraphStatusRequest.FromString,
                    response_serializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.GraphStatusResponse.SerializeToString,
            ),
            'StopGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.StopGraph,
                    request_deserializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.StopGraphRequest.FromString,
                    response_serializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.StopGraphResponse.SerializeToString,
            ),
            'ReadStdSlots': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadStdSlots,
                    request_deserializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.ReadStdSlotsRequest.FromString,
                    response_serializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.ReadStdSlotsResponse.SerializeToString,
            ),
            'GetAvailablePools': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailablePools,
                    request_deserializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.GetAvailablePoolsRequest.FromString,
                    response_serializer=ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.GetAvailablePoolsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.lzy.v1.workflow.LzyWorkflowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LzyWorkflowService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.lzy.v1.workflow.LzyWorkflowService/CreateWorkflow',
            ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.CreateWorkflowRequest.SerializeToString,
            ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.CreateWorkflowResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AttachWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.lzy.v1.workflow.LzyWorkflowService/AttachWorkflow',
            ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.AttachWorkflowRequest.SerializeToString,
            ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.AttachWorkflowResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FinishWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.lzy.v1.workflow.LzyWorkflowService/FinishWorkflow',
            ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.FinishWorkflowRequest.SerializeToString,
            ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.FinishWorkflowResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.lzy.v1.workflow.LzyWorkflowService/DeleteWorkflow',
            ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.DeleteWorkflowRequest.SerializeToString,
            ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.DeleteWorkflowResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.lzy.v1.workflow.LzyWorkflowService/ExecuteGraph',
            ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.ExecuteGraphRequest.SerializeToString,
            ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.ExecuteGraphResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GraphStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.lzy.v1.workflow.LzyWorkflowService/GraphStatus',
            ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.GraphStatusRequest.SerializeToString,
            ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.GraphStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.lzy.v1.workflow.LzyWorkflowService/StopGraph',
            ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.StopGraphRequest.SerializeToString,
            ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.StopGraphResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadStdSlots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ai.lzy.v1.workflow.LzyWorkflowService/ReadStdSlots',
            ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.ReadStdSlotsRequest.SerializeToString,
            ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.ReadStdSlotsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAvailablePools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.lzy.v1.workflow.LzyWorkflowService/GetAvailablePools',
            ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.GetAvailablePoolsRequest.SerializeToString,
            ai_dot_lzy_dot_v1_dot_workflow_dot_workflow__service__pb2.GetAvailablePoolsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
