{
 "title": "main dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Started tasks per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "toUnixTimestamp(timestamp)",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT toDateTime((intDiv(t, 60) * 60)) AS t, sum(tps) as tpm FROM\n\n(SELECT toUnixTimestamp(timestamp) as t, count() as tps FROM\n    (SELECT\n         JSON_VALUE(message, '$.event.type') as type,\n         JSONExtractRaw(JSONExtractRaw(message, 'event'), 'tags') as tags,\n         timestamp\n     FROM default.servant_logs WHERE logger = 'UserEventLogs')\nWHERE type = 'ExecutionStart'\nGROUP BY t\nORDER BY t)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT toDateTime((intDiv(t, 60) * 60)) AS t, sum(tps) as tpm FROM\n\n(SELECT toUnixTimestamp(timestamp) as t, count() as tps FROM\n    (SELECT\n         JSON_VALUE(message, '$.event.type') as type,\n         JSONExtractRaw(JSONExtractRaw(message, 'event'), 'tags') as tags,\n         timestamp\n     FROM default.servant_logs WHERE logger = 'UserEventLogs')\nWHERE type = 'ExecutionStart'\nGROUP BY t\nORDER BY t)\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "servant_logs"
    }
   ]
  },
  {
   "title": "ok/not ok tasks per last day",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "toUnixTimestamp(timestamp)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT toDateTime(t) as t, ok, not_ok FROM (\nSELECT intDiv(t, 60 * 60 * 24) * 60 * 60 * 24 AS t, sum(good) as ok, sum(bad) as not_ok FROM\n\n(SELECT toUnixTimestamp(timestamp) as t, countIf(JSONExtractString(tags, 'exit_code') = '0') as good, countIf(JSONExtractString(tags, 'exit_code') != '0') as bad FROM\n    (SELECT\n         JSON_VALUE(message, '$.event.type') as type,\n         JSONExtractRaw(JSONExtractRaw(message, 'event'), 'tags') as tags,\n         timestamp\n     FROM default.servant_logs WHERE logger = 'UserEventLogs')\nWHERE type = 'ExecutionComplete'\nGROUP BY t\nORDER BY t)\nGROUP BY t\nHAVING t = max(t)\nORDER BY t)\n",
     "rawQuery": "SELECT toDateTime(t) as t, ok, not_ok FROM (\nSELECT intDiv(t, 60 * 60 * 24) * 60 * 60 * 24 AS t, sum(good) as ok, sum(bad) as not_ok FROM\n\n(SELECT toUnixTimestamp(timestamp) as t, countIf(JSONExtractString(tags, 'exit_code') = '0') as good, countIf(JSONExtractString(tags, 'exit_code') != '0') as bad FROM\n    (SELECT\n         JSON_VALUE(message, '$.event.type') as type,\n         JSONExtractRaw(JSONExtractRaw(message, 'event'), 'tags') as tags,\n         timestamp\n     FROM default.servant_logs WHERE logger = 'UserEventLogs')\nWHERE type = 'ExecutionComplete'\nGROUP BY t\nORDER BY t)\nGROUP BY t\nHAVING t = max(t)\nORDER BY t)",
     "round": "0s",
     "table": "servant_logs"
    }
   ]
  },
  {
   "title": "Tasks by users per last day",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT uid, count FROM (\nSELECT\n       JSONExtractString(tags, 'user_id') as uid,\n       count() as count,\n       (intDiv(timestamp, 60 * 60 * 24) * 60 * 60 * 24) as t\nFROM (\n        SELECT\n             JSON_VALUE(message, '$.event.type') as type,\n             JSONExtractRaw(JSONExtractRaw(message, 'event'), 'tags') as tags,\n             toUnixTimestamp(timestamp) as timestamp\n         FROM default.server_logs WHERE logger = 'UserEventLogs'\n)\nWHERE type = 'TaskCreate'\nGROUP BY uid, t\nHAVING t = max(t)\nORDER BY t)\n",
     "rawQuery": "SELECT uid, count FROM (\nSELECT\n       JSONExtractString(tags, 'user_id') as uid,\n       count() as count,\n       (intDiv(timestamp, 60 * 60 * 24) * 60 * 60 * 24) as t\nFROM (\n        SELECT\n             JSON_VALUE(message, '$.event.type') as type,\n             JSONExtractRaw(JSONExtractRaw(message, 'event'), 'tags') as tags,\n             toUnixTimestamp(timestamp) as timestamp\n         FROM default.server_logs WHERE logger = 'UserEventLogs'\n)\nWHERE type = 'TaskCreate'\nGROUP BY uid, t\nHAVING t = max(t)\nORDER BY t)",
     "round": "0s"
    }
   ]
  }
 ]
}