storage:
  address: 'localhost:7780'

  iam:
    address: 'localhost:8443'
    internal-user-name: "lzy-internal-user"
    internal-user-private-key: "not-set"

  database:
    url: 'jdbc:postgresql://localhost:5432/lzy_storage_db'
    username: 'lzy_user'
    password: 'q'
    min-pool-size: 3
    max-pool-size: 5

  yc:
    enabled: false
    service-account-id: 'service-account-id'
    key-id: 'key-id'
    private-key: 'private-key'
    folder-id: 'folder-id'

  s3:
    yc:
      enabled: false
      endpoint: ''
      access-token: ''
      secret-token: ''

    azure:
      enabled: false
      connection-string: ''

    memory:
      enabled: false
      port: 18081
