apiVersion: v1
kind: Pod
metadata:
  name: lzy-servant
  labels:
    app: lzy-servant
spec:
  containers:
    - name: lzy-servant
      image: lzydock/lzy-servant:master
      imagePullPolicy: Always
      env:
        - name: LOGS_SERVER
          value: "kafka.default.svc.cluster.local:9092"
        - name: LOGS_APPENDER
          value: "Kafka"
        - name: LOGS_USERNAME
          valueFrom:
            secretKeyRef:
              name: kafka-servant
              key: username
        - name: LOGS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-servant
              key: password
        - name: LOG_FILE
          value: "servant.log"
        - name: SUSPEND_DOCKER
          value: n
        - name: DEBUG_PORT
          value: 5006
        - name: LZYHOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      args: ["--lzy-address", "$(LZY_SERVER_URI)", "--lzy-mount", "/tmp/lzy", "--host", "$(LZYHOST)", "--port", "9999"]
      ports:
        - containerPort: 9999
      securityContext:
        privileged: true
  restartPolicy: OnFailure
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - lzy-servant
                  - lzy-server
                  - lzy-kharon
                  - lzy-backoffice
          topologyKey: "kubernetes.io/hostname"
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
