"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class EnvSpec(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BASEENV_FIELD_NUMBER: builtins.int
    AUXENV_FIELD_NUMBER: builtins.int
    @property
    def baseEnv(self) -> global___BaseEnv: ...
    @property
    def auxEnv(self) -> global___AuxEnv: ...
    def __init__(
        self,
        *,
        baseEnv: global___BaseEnv | None = ...,
        auxEnv: global___AuxEnv | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["auxEnv", b"auxEnv", "baseEnv", b"baseEnv"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["auxEnv", b"auxEnv", "baseEnv", b"baseEnv"]) -> None: ...

global___EnvSpec = EnvSpec

@typing_extensions.final
class BaseEnv(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

global___BaseEnv = BaseEnv

@typing_extensions.final
class AuxEnv(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PYENV_FIELD_NUMBER: builtins.int
    @property
    def pyenv(self) -> global___PythonEnv: ...
    def __init__(
        self,
        *,
        pyenv: global___PythonEnv | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["env", b"env", "pyenv", b"pyenv"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["env", b"env", "pyenv", b"pyenv"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["env", b"env"]) -> typing_extensions.Literal["pyenv"] | None: ...

global___AuxEnv = AuxEnv

@typing_extensions.final
class PythonEnv(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    YAML_FIELD_NUMBER: builtins.int
    LOCALMODULES_FIELD_NUMBER: builtins.int
    name: builtins.str
    yaml: builtins.str
    @property
    def localModules(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LocalModule]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        yaml: builtins.str = ...,
        localModules: collections.abc.Iterable[global___LocalModule] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["localModules", b"localModules", "name", b"name", "yaml", b"yaml"]) -> None: ...

global___PythonEnv = PythonEnv

@typing_extensions.final
class LocalModule(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    URI_FIELD_NUMBER: builtins.int
    name: builtins.str
    uri: builtins.str
    """todo: ssokolvyak -- rename to url"""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        uri: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name", "uri", b"uri"]) -> None: ...

global___LocalModule = LocalModule

@typing_extensions.final
class Provisioning(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Tag(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TAG_FIELD_NUMBER: builtins.int
        tag: builtins.str
        def __init__(
            self,
            *,
            tag: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["tag", b"tag"]) -> None: ...

    TAGS_FIELD_NUMBER: builtins.int
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Provisioning.Tag]: ...
    def __init__(
        self,
        *,
        tags: collections.abc.Iterable[global___Provisioning.Tag] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["tags", b"tags"]) -> None: ...

global___Provisioning = Provisioning
