# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai/lzy/v1/common/slot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.lzy.v1.common import data_scheme_pb2 as ai_dot_lzy_dot_v1_dot_common_dot_data__scheme__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61i/lzy/v1/common/slot.proto\x12\tai.lzy.v1\x1a\"ai/lzy/v1/common/data-scheme.proto\"\xfc\x01\n\x04Slot\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x05media\x18\x02 \x01(\x0e\x32\x15.ai.lzy.v1.Slot.Media\x12,\n\tdirection\x18\x04 \x01(\x0e\x32\x19.ai.lzy.v1.Slot.Direction\x12*\n\x0b\x63ontentType\x18\x03 \x01(\x0b\x32\x15.ai.lzy.v1.DataScheme\"5\n\x05Media\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x08\n\x04\x46ILE\x10\x01\x12\x08\n\x04PIPE\x10\x02\x12\x07\n\x03\x41RG\x10\x03\"/\n\tDirection\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05INPUT\x10\x01\x12\n\n\x06OUTPUT\x10\x02\"\xfe\x01\n\nSlotStatus\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12$\n\x0b\x64\x65\x63laration\x18\x02 \x01(\x0b\x32\x0f.ai.lzy.v1.Slot\x12\x13\n\x0b\x63onnectedTo\x18\x03 \x01(\t\x12\x0f\n\x07pointer\x18\x04 \x01(\x04\x12*\n\x05state\x18\x05 \x01(\x0e\x32\x1b.ai.lzy.v1.SlotStatus.State\"h\n\x05State\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNBOUND\x10\x01\x12\r\n\tPREPARING\x10\x02\x12\x08\n\x04OPEN\x10\x03\x12\r\n\tSUSPENDED\x10\x04\x12\n\n\x06\x43LOSED\x10\x05\x12\r\n\tDESTROYED\x10\x06\"a\n\x0cSlotInstance\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x1d\n\x04slot\x18\x02 \x01(\x0b\x32\x0f.ai.lzy.v1.Slot\x12\x0f\n\x07slotUri\x18\x03 \x01(\t\x12\x11\n\tchannelId\x18\x04 \x01(\tB\x17\n\x10\x61i.lzy.v1.commonB\x03LMSb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.lzy.v1.common.slot_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\020ai.lzy.v1.commonB\003LMS'
  _SLOT._serialized_start=79
  _SLOT._serialized_end=331
  _SLOT_MEDIA._serialized_start=229
  _SLOT_MEDIA._serialized_end=282
  _SLOT_DIRECTION._serialized_start=284
  _SLOT_DIRECTION._serialized_end=331
  _SLOTSTATUS._serialized_start=334
  _SLOTSTATUS._serialized_end=588
  _SLOTSTATUS_STATE._serialized_start=484
  _SLOTSTATUS_STATE._serialized_end=588
  _SLOTINSTANCE._serialized_start=590
  _SLOTINSTANCE._serialized_end=687
# @@protoc_insertion_point(module_scope)
