lzy-service:
  address: 'localhost:8899'
  external-host: 'api.lzy.ai'
  server-address: 'localhost:7777'
  whiteboard-address: 'localhost:8999'
  snapshot-address: 'localhost:8999'
  channel-manager-address: 'localhost:8122'
  channel-manager-proxy-port: 8123
  allocator-address: 'localhost:8899'
  servant-proxy-port: 8900
  servant-fs-proxy-port: 8901

  database:
    url: 'jdbc:postgresql://localhost:5432/lzy_workflows_db'
    username: 'lzy_user'
    password: 'q'
    min-pool-size: 1
    max-pool-size: 5

  storage:
    address: 'localhost:7780'

  iam:
    address: 'localhost:8443'
    internal-user-name: "lzy-internal-user"
    internal-user-private-key: ""
