portal:
  portal-id: "portal"
  host: "localhost"
  portal-api-port: 7001
  slots-api-port: 7002
  stdout-channel-id: "${portal.portal-id}:stdout"
  stderr-channel-id: "${portal.portal-id}:stderr"
  channel-manager-address: "localhost:8122"
  whiteboard-address: "localhost:8999"
  iam-address: "localhost:8443"
  allocator-token: "token_${portal.portal-id}"
  vm-id: "portal-vm"
  allocator-address: "localhost:8799"
  allocator-heartbeat-period: 10m
  concurrency:
    workers-pool-size: 10
    downloads-pool-size: 10
    chunks-pool-size: 10
