channel-manager:
  address: 'localhost:8122'
  whiteboard-address: 'localhost:8999'
  iam:
    address: 'localhost:8443'
  database:
    url: "jdbc:h2:mem:testdb_iam;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;NON_KEYWORDS=USER;DATABASE_TO_UPPER=false"
    username: "test"
    password: ""
    enabled: true
    min-pool-size: 5
    max-pool-size: 100
