name: 'Cluster tests'

on:
  workflow_call:
    secrets:
      TESTS_PRIVATE_SSH_KEY:
        required: true



jobs:
  maven-test:
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: 'Copy secret key'
        env:
          PRIVATE_KEY: ${{ secrets.TESTS_PRIVATE_SSH_KEY }}
        run: touch /tmp/test-private.pem && echo "$PRIVATE_KEY" > /tmp/test-private.pem

      - name: 'AC test'
        timeout-minutes: 45
        run: mvn install -Dlzy.kharon.domain=kharon-lzy-prod.northeurope.cloudapp.azure.com -Dtest=KuberRunTest -DfailIfNoTests=false
