name: Package build and PyPI publish

on:
  workflow_call:
    secrets:
      PYPI_API_TOKEN:
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel

      - name: Build package
        run: |
          cp .git/HEAD pylzy/
          cd pylzy/
          pip install -r requirements.txt
          python setup.py sdist bdist_wheel

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          packages_dir: pylzy/dists
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
