allocator:

  service-clusters:
    - 'sys_cluster_1'
    - 'sys_cluster_2'

  user-clusters:
    - 'user_cluster_1'
    - 'user_cluster_2'
    - 'user_cluster_3'

  yc-mk8s:
    enabled: true
    service-account: 'dead-beef'
    service-account-secret: 'env variable name'

  azure-mk8s:
    enabled: false

  database:
    url: 'jdbc:h2:mem:testdb_ge;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false'
    username: 'test'
    password: ''
    min-pool-size: 1
    max-pool-size: 1
    enabled: true
