allocator:
  database:
    url: 'jdbc:h2:mem:testdb_ge;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false'
    username: 'test'
    password: ''
    min-pool-size: 1
    max-pool-size: 1
    enabled: true

  yc-mk8s:
    enabled: false

  azure-mk8s:
    enabled: false

  mock-mk8s:
    enabled: true