allocator:

  service-clusters: []

  user-clusters:
    - 'some-cluster'

  yc-mk8s:
    enabled: true
    service-account-file: "<path-to-sa-file>"

  azure-mk8s:
    enabled: false

  port: 1234
  gc-period: 30s
  heartbeat-timeout: 1m
  allocation-timeout: 15m

  kuber-allocator:
    enabled: true

  database:
    url: 'jdbc:h2:mem:testdb_ge;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false'
    username: 'test'
    password: ''
    min-pool-size: 1
    max-pool-size: 2
    enabled: true
