kharon:
  address: 'localhost:8899'
  external-host: 'api.lzy.ai'
  server-address: 'localhost:7777'
  whiteboard-address: 'localhost:8999'
  snapshot-address: 'localhost:8999'
  channel-manager-address: 'localhost:8122'
  channel-manager-proxy-port: 8123
  servant-proxy-port: 8900
  servant-fs-proxy-port: 8901

  database:
    url: 'jdbc:postgresql://localhost:5432/lzy_kharon_db'
    username: 'lzy_user'
    password: 'q'
    min-pool-size: 1
    max-pool-size: 5
