#kharon:
#  address: 'localhost:8899'
#  external-host: 'api.lzy.ai'
#  iam-address: 'localhost:7778'
#  server-address: 'localhost:7777'
#  whiteboard-address: 'localhost:8999'
#  snapshot-address: 'localhost:8999'
#  servant-proxy-port: 8900
#  servant-proxy-fs-port: 8901
#
#  workflow:
#    server-address: 'localhost:7777'
#    database:
#      url: 'jdbc:postgresql://localhost:5432/lzy_db'
#      username: 'lzy_user'
#      password: 'q'
#      min-pool-size: 1
#      max-pool-size: 5
