kharon:
  address: 'localhost:8899'
  # external-host: ''

  server-address: 'localhost:7777'
  whiteboard-address: 'localhost:8999'
  snapshot-address: 'localhost:8999'
  channel-manager-address: 'localhost:8122'

  servant-proxy-port: 8900
  servant-fs-proxy-port: 8901
  channel-manager-proxy-port: 8123

  database:
    url: 'embedded-postgres'
    username: 'test'
    password: ''
    min-pool-size: 3
    max-pool-size: 5
