storage:
  address: 'localhost:7780'

  database:
    url: 'jdbc:postgresql://localhost:5432/lzy_storage_db'
    username: 'lzy_user'
    password: 'q'
    min-pool-size: 1
    max-pool-size: 5

  yc:
    enabled: false

  s3:
    memory:
      enabled: true
      port: 18081
