storage:
  address: 'localhost:7780'

  database:
    url: 'jdbc:postgresql://localhost:5432/lzy_db'
    username: 'lzy_user'
    password: 'q'
    min-pool-size: 1
    max-pool-size: 5

  amazon:
    enabled: false
    endpoint: ''
    access-token: ''
    secret-token: ''

  azure:
    enabled: false
    connection-string: ''

  memory:
    enabled: false
