storage:
  address: 'localhost:7780'

  database:
  url: 'jdbc:h2:mem:testdb_storage;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false'
  username: 'test'
  password: ''
  min-pool-size: 1
  max-pool-size: 1

  yc:
    enabled: false

  s3:
    memory:
      enabled: true
      port: 18081
