routes:
  - input:
      plugin: metrics_pull
      config:
        url: http://localhost:17080
        format:
          prometheus: {}
        namespace: "allocator"
    channel:
      channel_ref:
        name: cloud_monitoring