name: 'AC tests'
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  maven-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - uses: docker-practice/actions-setup-docker@master

      - name: 'AC test'
        timeout-minutes: 45
        run: mvn install -Dtest=KuberRunTest -DfailIfNoTests=false

      - name: Publish Test Report
          uses: mikepenz/action-junit-report@v2
          if: always()