name: 'Cron cluster tests'
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  acceptance-tests:
      uses: lambda-zy/lzy/.github/workflows/acceptance-tests.yml@master
      secrets:
        TESTS_PRIVATE_SSH_KEY: ${{ secrets.TESTS_PRIVATE_SSH_KEY }}