name: 'Cron cluster tests'
on:
  schedule:
    - cron: '0 21 * * *' # 24:00 Moscow Time: UTC+3
  workflow_dispatch:

jobs:
  #### <- TODO: replace with reusable workflow in future: .github/workflows/reusable/acceptance-tests.yml

  acceptance-test:
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev # run acceptance-test on dev branch

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: 'Copy secret key'
        env:
          PRIVATE_KEY: ${{ secrets.TESTS_PRIVATE_SSH_KEY }}
        run: touch /tmp/test-private.pem && echo "$PRIVATE_KEY" > /tmp/test-private.pem

      - name: 'Clean'
        run: sudo iptables -t filter -F && sudo iptables -t filter -X && sudo systemctl restart docker

      - name: 'AC test'
        timeout-minutes: 45
        run: mvn install -Dlzy.kharon.domain=api.lzy.ai -Dtest=KuberRunTest -DfailIfNoTests=false

  #### <- TODO: replace with reusable workflow in future: .github/workflows/reusable/acceptance-tests.yml
