name: 'Cron cluster tests'
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  #### <- TODO: replace with reusable workflow in future: .github/workflows/reusable/acceptance-tests.yml

  acceptance-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - run: git checkout dev # run acceptance on dev branch

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: 'build-base-image'
        timeout-minutes: 10
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          context: ./
          file: ./lzy-servant/BaseDockerfile
          tags: celdwind/lzy:lzy-servant-base

      - name: 'Copy secret key'
        env:
          PRIVATE_KEY: ${{ secrets.TESTS_PRIVATE_SSH_KEY }}
        run: touch /tmp/test-private.pem && echo "$PRIVATE_KEY" > /tmp/test-private.pem

      - name: 'AC test'
        timeout-minutes: 45
        run: mvn install -Dlzy.kharon.domain=kharon-lzy-prod.northeurope.cloudapp.azure.com -Dtest=KuberRunTest -DfailIfNoTests=false

  #### <- TODO: replace with reusable workflow in future: .github/workflows/reusable/acceptance-tests.yml
