name: Publish allocator api
on:
  workflow_dispatch:

jobs:

  all-tests:
    runs-on: self-hosted
    timeout-minutes: 60
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: "Chown for checkout"
        run: sudo chown -R $USER:$USER /home/ubuntu/actions-runner/_work/lzy/

      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup maven settings"
        uses: s4u/maven-settings-action@v2.6.0
        with:
          servers: |
            [{
              "id": "repsy",
              "username": "lzy",
              "password": "${{ secrets.REPSY_PASSWORD }}"
            }]

      - name: "Publish parent"
        timeout-minutes: 10
        run: |
          cd parent/ && mvn clean deploy --also-make-dependents && cd ..

      - name: "Publish util-grpc"
        timeout-minutes: 10
        run: |
          cd util/util-grpc/ && mvn clean deploy --also-make-dependents && cd ../..

      - name: "Publish util-auth"
        timeout-minutes: 10
        run: |
          cd util/util-auth/ && mvn clean deploy --also-make-dependents && cd ../..

      - name: "Publish operation api"
        timeout-minutes: 10
        run: |
          cd long-running-api/ && mvn clean deploy --also-make-dependents && cd ..

      - name: "Publish allocator api"
        timeout-minutes: 10
        run: |
          cd lzy/allocator-api/ && mvn clean deploy --also-make-dependents && cd ../..

      - name: "Publish model"
        timeout-minutes: 10
        run: |
          cd model/ && mvn clean deploy --also-make-dependents && cd ..

      - name: "Publish whiteboard api"
        timeout-minutes: 10
        run: |
          cd whiteboard-api/ && mvn clean deploy --also-make-dependents && cd ..
