name: Package build and PyPI publish

on:
  workflow_call:
    inputs:
      checkout_dev:
        required: false
        type: boolean
        default: false

    secrets:
      PYPI_API_TOKEN:
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: inputs.checkout_dev
        with:
          ref: 'dev'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: cp .git/HEAD lzy-python/ && cd lzy-python/ && python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          packages_dir: lzy-python/dists
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
