name: Update dockers
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: 'Tag name for images'
        required: false
        default: ''
      update:
        type: boolean
        description: 'Tag with new minor version instead of custom tag for images'
        required: false
        default: true
      servant-base:
        type: boolean
        description: 'Update base servant docker image'
        required: false
        default: false
jobs:

  build-and-push-dockers:
    runs-on: self-hosted
#    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 'Build and push servant-base'
        if: ${{ github.event.inputs.servant-base }}
        run: |
          FLAGS=""
          if [[ ${{ github.event.inputs.update }} == true ]]; then FLAGS="--update"; fi
          bash deployment/push-servant-base-docker.sh "${{ github.ref_name }}" "${{ github.event.inputs.tag }}" $FLAGS

      - name: 'Build and push all dockers'
        run: |
          FLAGS="--rebuild"
          if [[ ${{ github.event.inputs.update }} == true ]]; then FLAGS="$FLAGS --update"; fi
          bash deployment/push-docker.sh "${{ github.ref_name }}" "${{ github.event.inputs.tag }}" $FLAGS

      - name: 'Clean docker files'
        run: |
          docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)
          docker image prune -f
          docker volume prune -f
