name: Update dockers
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: 'Tag name for images'
        required: false
        default: ''
      update:
        type: boolean
        description: 'Tag with new minor version instead of custom tag for images'
        required: false
        default: false
      servant-base:
        type: boolean
        description: 'Update base servant docker image'
        required: false
        default: false
jobs:

  build-and-push-dockers:
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: 'push-docker'
        run: |
          FLAGS="--rebuild"
          if [[ ${{ github.event.inputs.update }} == true ]]; then FLAGS="$FLAGS --update"; fi
          if [[ ${{ github.event.inputs.servant-base }} == true ]]; then FLAGS="$FLAGS --base"; fi
          bash deployment/push-docker.sh "${{ github.ref_name }}" "${{ github.event.inputs.tag }}" $FLAGS