name: Update dockers
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: 'Tag name for images'
        required: false
        default: ''
      update:
        type: boolean
        description: 'Tag with new minor version instead of custom tag for images'
        required: false
        default: true
      servant-base:
        type: boolean
        description: 'Update base servant docker image'
        required: false
        default: false
jobs:

  build-and-push-dockers:
    runs-on: self-hosted
#    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}

      - uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: 'push-docker'
        run: |
          FLAGS="--rebuild"
          if [[ ${{ github.event.inputs.update }} == true ]]; then FLAGS="$FLAGS --update"; fi
          if [[ ${{ github.event.inputs.servant-base }} == true ]]; then FLAGS="$FLAGS --base"; fi
          bash deployment/push-docker.sh "${{ github.ref_name }}" "${{ github.event.inputs.tag }}" $FLAGS

      - name: 'Delete docker images'
        run: |
          docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)
          export REUSED_BASE_IMAGES="findepi/graalvm:java17-all|nvidia/cuda:11.2.0-devel-ubuntu20.04|lzydock/lzy-servant-base:master"
          docker image rm $(docker image ls -q | grep -v "$(docker image ls --format "{{.ID}}\t{{.Repository}}:{{.Tag}}" | grep -E "$REUSED_BASE_IMAGES" | awk '{print $1}')")