name: Publish dev pylzy-nightly package

on:
  schedule:
    - cron: '59 20 * * *' # run everyday on 23:59 Moscow Time: UTC+3
  workflow_dispatch:

jobs:
  #### <- TODO: replace with reusable workflow in future: .github/workflows/reusable/acceptance-tests.yml
  acceptance-test:
#    runs-on: self-hosted
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2 # TODO: should it run in master or in dev?
        with:
          fetch-depth: 0

      - run: git checkout dev

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: 'Copy secret key'
        env:
          PRIVATE_KEY: ${{ secrets.TESTS_PRIVATE_SSH_KEY }}
        run: touch /tmp/test-private.pem && echo "$PRIVATE_KEY" > /tmp/test-private.pem

      - name: 'AC test'
        timeout-minutes: 45
        run: mvn install -Dlzy.kharon.domain=api.lzy.ai -Dtest=KuberRunTest -DfailIfNoTests=false

      - uses: scacap/action-surefire-report@v1

  #### <- TODO: replace with reusable workflow in future: .github/workflows/reusable/acceptance-tests.yml


  #### <- TODO: replace with reusable workflow in future: .github/workflows/reusable/build-pypi-publish.yml
  build-and-publish:
    needs: acceptance-test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: git checkout dev

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel

      - name: Build package
        run: |
          cp .git/HEAD lzy-python/
          cd lzy-python/
          pip install -r requirements.txt
          python setup.py sdist --dev bdist_wheel --dev
          cd ..

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          packages_dir: ./lzy-python/dist
          user: __token__
          password: ${{ secrets.PYPI_API_NIGHTLY_TOKEN }}
  #### <- TODO: replace with reusable workflow in future: .github/workflows/reusable/build-pypi-publish.yml
