name: Publish dev pylzy-nightly package

on:
  schedule:
    - cron: 59 23 * * * # run everyday on 23:59

jobs:
  build-and-publish:
    uses: lambda-zy/lzy/.github/workflows/build-pypi-publish.yml@master
    with:
      dev: true # checkout to dev branch before running
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
