name: Lint python

on:
  pull_request:
    paths:
      - 'pylzy/lzy/**'
      - 'jupyter-kernel/lzy/**'

jobs:
  mypy:
    runs-on: self-hosted
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install mypy
        run: pip install mypy && pip install -r pylzy/requirements.txt && pip install -r pylzy/lint_requirements.txt
      - name: Run mypy
        uses: tsuyoshicho/action-mypy@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error
          workdir: pylzy
      - name: Run mypy on DS
        uses: tsuyoshicho/action-mypy@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error
          workdir: jupyter-kernel
