name: Lint python

on:
  pull_request:
    paths:
      - 'lzy-python/lzy/**'
      - 'ds-ide-kernel/lzy/**'

jobs:
  mypy:
    runs-on: self-hosted
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install mypy
        run: pip install mypy && pip install -r lzy-python/requirements.txt && pip install -r lzy-python/lint_requirements.txt
      - name: Run mypy
        uses: tsuyoshicho/action-mypy@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error
          workdir: lzy-python
      - name: Run mypy on DS
        uses: tsuyoshicho/action-mypy@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error
          workdir: ds-ide-kernel
