name: Publish release pylzy package

on:
  push:
    branches:
      - 'main'
    paths:
      - 'lzy-python/version' # TODO: replace with tag change?
jobs:
  run-tests:
    uses: lambda-zy/lzy/.github/workflows/run-tests.yml@main

  build-and-publish:
    needs: run-tests
    uses: lambda-zy/lzy/.github/workflows/build-pypi-publish.yml@main
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
