name: Publish release pylzy package

on:
  push:
    branches:
      - master
    paths:
      - lzy-python/version # TODO: replace with tag change?
  workflow_dispatch:

jobs:
  #### <- TODO: replace with reusable workflow in future: .github/workflows/reusable/acceptance-tests.yml
  acceptance-test:
#    runs-on: self-hosted
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: 'Copy secret key'
        env:
          PRIVATE_KEY: ${{ secrets.TESTS_PRIVATE_SSH_KEY }}
        run: touch /tmp/test-private.pem && echo "$PRIVATE_KEY" > /tmp/test-private.pem

      - name: 'AC test'
        timeout-minutes: 45
        run: mvn install -Dlzy.kharon.domain=api.lzy.ai -Dtest=KuberRunTest -DfailIfNoTests=false

      - uses: scacap/action-surefire-report@v1
        if: always()

  #### <- TODO: replace with reusable workflow in future: .github/workflows/reusable/acceptance-tests.yml


  #### <- TODO: replace with reusable workflow in future: .github/workflows/reusable/build-pypi-publish.yml
  build-and-publish:
    needs: acceptance-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - run: cd lzy-python
      - name: Build package
        run: ./clean.sh && ./build.sh

      - name: Publish package
        run: ./publish.sh
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_RELEASE_TOKEN }}

      - name: Clean up
        run: ./clean.sh && cd ..
  #### <- TODO: replace with reusable workflow in future: .github/workflows/reusable/build-pypi-publish.yml
