name: 'Tests'
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  maven-test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - uses: docker-practice/actions-setup-docker@master

      - name: 'java-test'
        timeout-minutes: 30
        run: mvn clean install

      - name: 'install lzy-python'
        run: cd lzy-python/ && pip install .

      - name: 'python-test'
        timeout-minutes: 5
        run:  cd lzy-python/ && python -m unittest discover tests/