name: Test on pull request
on:
  push:
    branches: [ master, dev ]
  pull_request:

jobs:

  #### <- TODO: replace with call to reusable workflow in future: .github/workflows/reusable/pull-request-workflow.yaml
  all-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: 'build-base-image'
        timeout-minutes: 10
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          context: ./
          file: ./lzy-servant/BaseDockerfile
          tags: celdwind/lzy:lzy-servant-base

      - name: 'java-test'
        timeout-minutes: 45
        run: mvn clean install

      - name: 'install lzy-python'
        run: cd lzy-python/ && pip install -r requirements.txt && pip install .

      - name: 'python-test'
        timeout-minutes: 5
        run: cd lzy-python/ && python -m unittest discover tests/
  #### <- TODO: replace with call to reusable workflow in future: .github/workflows/reusable/pull-request-workflow.yaml
