name: 'Sync master and dev'

on:
  workflow_dispatch:

jobs:
  nightly-merge:
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: git checkout dev
      - run: git rev-parse --abbrev-ref HEAD

      #### <- TODO: replace with call or even action in future: .github/workflows/reusable/pull-request-workflow.yaml
#      - uses: actions/setup-java@v3
#        with:
#          distribution: 'adopt'
#          java-version: '17'
#
#      - uses: actions/setup-python@v2
#        with:
#          python-version: '3.8'
#
#      - name: 'java-test'
#        timeout-minutes: 45
#        run: mvn clean install
#
#      - name: 'install pylzy'
#        run: cd pylzy/ && pip install -r requirements.txt && pip install .
#
#      - name: 'python-test'
#        timeout-minutes: 5
#        run: cd pylzy/ && python -m unittest discover tests/
      #### <- TODO: replace with call or even action in future: .github/workflows/reusable/pull-request-workflow.yaml

      - name: Merge
        run: |
          git checkout master
          git merge --ff-only dev

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master