name: 'Sync release branch'

on:
  push:
    branches:
      - 'release-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'
      - 'release-test'
  workflow_dispatch:

jobs:
  pull-request-from-release-branch:
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - name: "Chown for checkout"
        run: sudo chown -R $USER:$USER /home/ubuntu/actions-runner/_work/lzy/

      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      # https://github.com/marketplace/actions/github-pull-request-action
      - name: "Create pull request"
        id: create-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "deploy-improvement" # TODO: ${{ github.event.repository.default_branch }}
          pr_title: "[Automated] Apply fixes from ${{ github.ref_name }}" # TODO: ${{ github.event.repository.default_branch }}"
          pr_body: "Automated Pull Request"
          pr_reviewer: "lindlind"
          pr_assignee: "lindlind"

      - run: echo "${{ steps.create-pr.outputs.pr_number }}"

      # https://github.com/marketplace/actions/enable-pull-request-automerge
      - name: "Enable automerge"
        if: steps.create-pr.outputs.pr_number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          pull-request-number: ${{ steps.create-pr.outputs.pr_number }}
          merge-method: squash