name: 'Sync release branch'

on:
  push:
    branches:
      - 'release-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'
      - 'release-test'
  workflow_dispatch:

jobs:
  pull-request-from-release-branch:
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # https://github.com/marketplace/actions/github-pull-request-action
      - name: "Create pull request"
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: "deploy-improvement" # TODO: ${{ github.event.repository.default_branch }}
          pr_title: "[Automated] Apply fixes from ${{ github.ref_name }}" # TODO: ${{ github.event.repository.default_branch }}"
          pr_body: "Automated Pull Request"
          pr_reviewer: "lindlind"
          pr_assignee: "lindlind"

      # https://github.com/marketplace/actions/enable-pull-request-automerge
      - name: "Enable automerge"
        if: steps.open-pr.outputs.pr_number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
          merge-method: squash