name: 'Sync release branch'

on:
  push:
    branches:
      - 'release-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'
  workflow_dispatch:

jobs:
  pull-request-from-release-branch:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - name: "Chown for checkout"
        run: sudo chown -R $USER:$USER /home/ubuntu/actions-runner/_work/lzy/

      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      # https://github.com/marketplace/actions/github-pull-request-action
      - name: "Create pull request"
        id: create-pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: ${{ github.event.repository.default_branch }}
          pr_title: "[Automated] Apply fixes from ${{ github.ref_name }}"
          pr_body: "Automated Pull Request"
          pr_reviewer: "lindlind"
          pr_assignee: "lindlind"

      # https://github.com/marketplace/actions/enable-pull-request-automerge
      - name: "Enable automerge"
        if: steps.create-pr.outputs.pr_number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create-pr.outputs.pr_number }}
          merge-method: squash


  echo:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - name: output-url
        run: echo ${{steps.create-pr.outputs.pr_url}}
      - name: output-number
        run: echo ${{steps.create-pr.outputs.pr_number}}
      - name: output-has-changed-files
        run: echo ${{steps.create-pr.outputs.has_changed_files}}

  unit-tests:
    if: steps.create-pr.outputs.pr_number != ''
    needs: pull-request-from-release-branch
    uses: ./.github/workflows/pull-tests.yml
    with:
      ref_name: ${{steps.open-pr.outputs.pr_url}}
