name: Update docker tag in push
on:
  push:

jobs:

  # TODO
  # 2) increment tags -
  update-docker-tags:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: 'extract docker tags'
        id: tags
        uses: docker/metadata-action@v3
        with:
          images: lzydock/lzy-server,lzydock/lzy-kharon,lzydock/lzy-servant,lzydock/lzy-whiteboard
          tags: |
            type=semver,pattern={{version}}

      - name: 'push-docker'
        run: echo "${{steps.tags.outputs.tags}}" | | awk '{for (i = 1; i <= NF; i++) {print $i}}' | awk -F ":" '{print $2}' | bash deployment/push-docker.sh {{branch}} rebuild update-version
